name: Deploy S3

on:
  push:
    branches:
      - s3
jobs:
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation

    strategy:
      matrix:
        ruby-version: [3.1]

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'hml-dev-portal'      # optional: defaults to entire repository