name: Deploy S3

on:
  push:
    branches:
      - s3
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'hml-dev-portal'
          source_dir: 'documentation'
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation

    strategy:
      matrix:
        ruby-version: [3.1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-${{ matrix.ruby-version }}-
            gems-${{ runner.os }}-
      # necessary to get ruby 2.3 to work nicely with bundler vendor/bundle cache
      # can remove once ruby 2.3 is no longer supported
      - run: gem update --system

      - run: bundle config set deployment 'true'
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec middleman build --verbose

      - uses: actions/checkout@v3

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'hml-dev-portal'
          source_dir: 'documentation'

      # - name: Push to S3
      #   uses: reggionick/s3-deploy@v3
      #   with:
      #     folder: build
      #     bucket: hml-dev-portal
      #     bucket-region: us-east-2
      #     # dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true
      #     filesToInclude: ".*/*,*/*,**"
      #   env:
      #     AWS_ACCESS_KEY_ID: AKIAUA7IUAYR3EYGVYVB
      #     AWS_SECRET_ACCESS_KEY: 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

