name: Deploy S3

on:
  push:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation/build

    strategy:
      matrix:
        ruby-version: [3.1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-${{ matrix.ruby-version }}-
            gems-${{ runner.os }}-
      - run: gem update --system

      - run: bundle config set deployment 'true'
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec middleman build --verbose

      - uses: actions/checkout@v3

      - name: Push to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: documentation/build
          bucket: hml-dev-portal
          bucket-region: us-east-2
          # dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
